[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://dental-ai-backend-55pq.onrender.com/api"

[[redirects]]
  from = "/api/*"
  to = "https://dental-ai-backend-55pq.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
